# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=400)),
                ('fecha_inicio', models.DateTimeField(verbose_name='fecha de inicio')),
                ('fecha_final_estimada', models.DateTimeField(verbose_name='fecha de finalizacion estimada')),
                ('porcentaje_completado', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tarea', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=400)),
                ('comentarios', models.CharField(max_length=400)),
                ('porcentaje_completado', models.PositiveIntegerField(default=0)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmmi.Proyecto')),
            ],
        ),
    ]
