# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 17:01
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=400)),
                ('fecha_inicio', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('manager', models.CharField(max_length=100, null=True)),
                ('porcentaje_completado', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tarea', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=400)),
                ('comentarios', models.CharField(blank=True, max_length=400)),
                ('porcentaje_completado', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmmi.Proyecto')),
            ],
        ),
    ]
