# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmmi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='tiene_preferencia',
            field=models.BooleanField(default=False),
        ),
    ]
