# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmmi', '0002_tarea_tiene_preferencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='tiene_preferencia',
            new_name='es_urgente',
        ),
    ]
