# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmmi', '0003_auto_20170803_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='porcentaje_completado',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='comentarios',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='porcentaje_completado',
        ),
    ]
