# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 20:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmmi', '0004_auto_20170730_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_final_estimada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha estimada de finalizacion'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='porcentaje_completado',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='porcentaje_completado',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
