# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmmi', '0006_auto_20170805_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='manager',
            field=models.CharField(max_length=100),
        ),
    ]
