# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmmi', '0007_auto_20170807_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='nivelMadurez',
            field=models.CharField(choices=[('Ejecutado', 'Ejecutado'), ('Gestionado', 'Gestionado'), ('Definido', 'Definido'), ('Gestionado Cuantitativamente', 'Gestionado Cuantitativamente'), ('Optimizado', 'Optimizado')], default='Incompleto', max_length=100),
        ),
        migrations.AddField(
            model_name='tarea',
            name='categoriaAP',
            field=models.CharField(choices=[('Gestión de proyecto', 'Gestión de proyecto'), ('Gestión de procesos', 'Gestión de procesos'), ('Ingeniería', 'Ingeniería'), ('Soporte', 'Soporte')], default='--', max_length=100),
        ),
    ]
